---
- name: restart apache
  service:
    name: "{{ apache_service }}"
    state: "{{ apache_restart_state }}"

- name: restart php-fpm
  service:
    name: php-fpm
    state: restarted
    daemon_reload: yes
