- name: Update RHEL
  hosts: emasesalnx
  serial: 5
  gather_facts: true
  tasks:

   - name: Identify openvm tools
     shell: rpm -qa | grep open-vm-tools
     register: vmtools
     ignore_errors: yes

   - name: Remove vmware tools
     command: /usr/bin/vmware-uninstall-tools.pl
     when: vmtools.rc == 1

   - name: Install open-vm-tools
     yum:
      name: open-vm-tools
      state: present

   - name: Update all packages
     yum:
      name: '*'
      state: latest

   - name: reboot system
     reboot:

   - name: wait for server to come back after reboot
     wait_for_connection:
       timeout: 600
       delay: 40
     register: reboot_result

   - name: reboot time
     debug:
       msg: "The system rebooted in {{ reboot_result.elapsed }} seconds."
       
- name: Start up application
  hosts: emasesalnx
  gather_facts: false
  roles:
     - startapp
     - httpd24httpd
     - httpd24
     - httpd
     - ssmc
     - eap7
     - jboss
     - jbosseap7
     - zabbix

