---
- hosts: aixsse
  tasks: 

   - name: Find files older than 7 days 
     find: 
      paths: /etc 
      patterns: 'rc.tcpip*'
      age: 7d
     register: hkfiles

   - debug:
       var: hkfiles
 
   - name: Delete files older than 7 days
     file:
      path: "{{ item.path }}"
      state: absent
     loop: "{{ hkfiles.files }}"
     

