---
- name: Harden tcp/ip
  hosts: havut226
  vars_files:
    - /etc/ansible/vars/hardening_vars.yml
  tasks:

     - name: Check TCP/IP parameters
       shell: no -x {{ item.setting }} | awk -F, '{print $2}' | grep {{ item.value }}
       register: noutput
       loop: "{{ tcpip }}"
       changed_when: false
       ignore_errors: yes

     - name: Harden TCP/IP parameters
       command: "no -p -o {{ item.item.setting }}={{ item.item.value }}"
       loop: "{{ noutput.results }}"
       when: "item.rc != 0"
       loop_control:
          label: "{{ item.item.setting }}"
